# Generated by Django 5.1.3 on 2024-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='multiapps',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
