# Generated by Django 5.1.3 on 2024-12-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_phrasekey_alter_multiapps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasekey',
            name='phrase_key',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='phrasekey',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto_app.multiapps'),
        ),
    ]
